version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: 
          command: npm ci
      - run:
          command: npm run build:production
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .