version: 2.1
orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.6
jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy: # this can be any name you choose
<<<<<<< HEAD
=======
    
>>>>>>> 5f42d856295548e5dbe773aacfe0c534609e28e0
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: "bloggingwebsite-backend"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
